#!/usr/bin/env python3
"""Load the MOPS statement channel into tlfx.firm_quarterly.

Source: data/mops_statements.csv (scripts/stage3_mops_parse.py, XBRL facts by
concept and context date). Conventions follow decisions 3.12 — NT$ mn,
vintage = period end, source_channel = 'statement'.

The FX-valuation reserve is a balance-sheet line through 2025 and disappears
from the IFRS-17 condensed balance sheet in 2026, exactly as it did for
Cathay; the same recovery applies — 2026 balance = the firm's own 2025Q4
balance plus the cash-flow statement's year-to-date net change. That
recovery is not assumed here, it is *verified against the decks* on two
independent firms (decisions 4.5):

    Fubon    142,124.635 + 5,264.372  = 147,389.0  vs deck 147.4 (Mar-26)
             142,124.635 + 11,552.634 = 153,677.3  vs deck 153.7 (Jun-26)
    KGI       43,370 (deck FY25) + 1,461.764 = 44,831.8 vs deck 44.83 (1Q26)
                                   + 5,621.52 = 48,991.5 vs deck 48.99 (1H26)

Only reserve balances whose base is a *statement* are loaded. That was Fubon
and Nan Shan until KGI's own 2025Q4 filing arrived (2026-09-05), which both
promotes KGI into this channel and independently confirms the recovery: the
statement puts the base at 43,372.327 against the deck's printed 43.37bn, a
0.005% gap that is the deck's own rounding. The derived 2026 balances move by
2.3mn and still tie the decks at 44.83 and 48.99.
"""
import csv
import datetime as dt
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "mops_statements.csv"
Q_END = {1: "03-31", 2: "06-30", 3: "09-30", 4: "12-31"}
URL = "https://mopsov.twse.com.tw/server-java/t164sb01"


def sqlv(v):
    if v is None:
        return "null"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    return str(v)


def num(s):
    return None if s in (None, "") else float(s)


def main():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8")))
    # 2025Q4 statement balances are the only admissible bases for the 2026
    # recovery: a deck-sourced base would put a deck number in the statement
    # channel under a statement's provenance.
    base = {r["entity_id"]: num(r["fx_reserve_mn"]) for r in rows
            if r["year"] == "2025" and r["q"] == "4" and num(r["fx_reserve_mn"])}

    out, checks = [], []
    for r in sorted(rows, key=lambda x: (x["entity_id"], x["year"], x["q"])):
        y, q = int(r["year"]), int(r["q"])
        res, note_extra = num(r["fx_reserve_mn"]), ""
        if res is None and y >= 2026 and r["entity_id"] in base:
            chg = num(r["fx_reserve_net_change_ytd_mn"])
            if chg is not None:
                res = round(base[r["entity_id"]] - chg, 3)  # charge is negative
                note_extra = (" FX reserve recovered as the firm's own 2025Q4 balance "
                              f"({base[r['entity_id']]:,.3f}) less the cash-flow YTD net "
                              f"change ({chg:,.3f}); the IFRS-17 condensed balance sheet "
                              "folds the line into other liabilities (decisions 3.12/4.5).")
        a, l, e = num(r["assets_mn"]), num(r["liabilities_mn"]), num(r["equity_mn"])
        ok = a is not None and l is not None and e is not None and abs(a - l - e) <= 0.5
        checks.append((f"A=L+E {r['entity_id']} {y}Q{q}", ok))
        rep = "consolidated" if r["report"] == "C" else "individual (no consolidated filing)"
        out.append({
            "entity": r["entity_id"], "obs": r["obs_quarter"],
            "vintage": f"{y}-{Q_END[q]}",
            "basis": "IFRS17" if y >= 2026 else "IFRS4",
            "res": res, "ta": a, "eq": e,
            "doc": f"MOPS t164sb01 {r['co_id']} {y}Q{q} {rep}, XBRL-rendered statements",
            "note": ("NT$ mn from NT$-thousand XBRL facts, matched by concept and context "
                     "date; vintage = period end." + note_extra),
        })

    now = dt.datetime.now(dt.timezone.utc).isoformat()
    cols = ["entity", "obs", "vintage", "basis", "res", "ta", "eq", "doc", "note"]
    vals = ",\n  ".join("(" + ", ".join(sqlv(r[c]) for c in cols) + ")" for r in out)
    sql = f"""-- stage3-mops-load: generated by scripts/stage3_load_mops.py at {now}. Idempotent.
begin;
with vals(entity_id, obs_quarter, vintage, basis, res, ta, eq, doc, note) as (values
  {vals})
insert into tlfx.firm_quarterly
  (entity_id, obs_quarter, vintage, basis, source_channel, fx_reserve_balance,
   total_assets, owners_equity, source_url, source_doc, source_note, retrieved_at)
select entity_id, obs_quarter::date, vintage::date, basis::tlfx.accounting_basis,
  'statement', res, ta, eq, '{URL}', doc, note, '{now}'::timestamptz
from vals
-- Fill-only upsert, not "do nothing". A quarter's row is often written before
-- every field is obtainable: KGI's 2026 rows landed with a NULL reserve
-- because the 2025Q4 base had not been fetched, and the base arriving later
-- must be able to complete them. coalesce keeps the stored value wherever one
-- exists, so this can only turn NULL into a figure, never overwrite a figure
-- with a different one -- a correction at the same vintage, which is what
-- this is, and not a revision, which would need a new vintage.
on conflict (entity_id, obs_quarter, basis, source_channel, vintage) do update set
  fx_reserve_balance = coalesce(firm_quarterly.fx_reserve_balance, excluded.fx_reserve_balance),
  total_assets       = coalesce(firm_quarterly.total_assets,       excluded.total_assets),
  owners_equity      = coalesce(firm_quarterly.owners_equity,      excluded.owners_equity),
  source_note        = case when firm_quarterly.fx_reserve_balance is null
                              and excluded.fx_reserve_balance is not null
                            then excluded.source_note
                            else firm_quarterly.source_note end;
commit;
"""
    tag = dt.date.today().strftime("%Y%m%d")
    p = ROOT / "out" / f"stage3_mops_load_{tag}.sql"
    p.write_text(sql, encoding="utf-8")

    keys = {(r["entity"], r["obs"], r["basis"], r["vintage"]) for r in out}
    assert len(keys) == len(out), "duplicate natural key"
    nok = sum(1 for _, o in checks if o)
    print(f"rows: {len(out)}; checks {nok}/{len(checks)}; "
          f"reserve balances: {sum(1 for r in out if r['res'] is not None)}")
    print(f"checksums: sum total_assets {round(sum(r['ta'] or 0 for r in out), 3)}; "
          f"sum equity {round(sum(r['eq'] or 0 for r in out), 3)}; "
          f"sum reserve {round(sum(r['res'] or 0 for r in out), 3)}")
    print(f"sql: {p.relative_to(ROOT)}")
    return 0 if nok == len(checks) else 1


if __name__ == "__main__":
    sys.exit(main())
