#!/usr/bin/env python3
"""Stage 3 load: data/cathay_fx_quarterly.csv -> tlfx.firm_quarterly (deck channel).

Maps the merged en/zh Cathay deck series onto the firm panel:
  period 1Q/1H/9M/FY + yy -> obs_quarter (first day of the period's end quarter)
  fx_assets_ntd_tn        -> foreign_assets, NT$ mn (x 1e6)
  fx_volatility_reserve_ntd_bn -> fx_reserve_balance, NT$ mn (x 1e3)
  hedging_cost_pct        -> hedge_cost_bp (x 100)
  wedge/split percentages -> *_share_pct columns (migration 0006)
  basis: IFRS17 for 2026-on periods, IFRS4 before
  vintage = deck_date; source_url from the language deck index (en wins)

Emits out/stage3_cathay_YYYYMMDD.sql (compact CTE, idempotent) and prints a
summary with local checksums for the post-load server-side verification.
"""
import csv
import datetime as dt
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MERGED = ROOT / "data" / "cathay_fx_quarterly.csv"
DECK_EN = ROOT / "data" / "cathay_deck_fx.csv"
DECK_ZH = ROOT / "data" / "cathay_deck_fx_zh.csv"

Q_START = {"1Q": "01-01", "1H": "04-01", "9M": "07-01", "FY": "10-01"}


def urls_by_date(path):
    out = {}
    if path.exists():
        with open(path, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                out[r["deck_date"]] = (r.get("pdf_url") or "", r.get("deck_title") or "")
    return out


def num(s):
    return None if s in (None, "") else float(s)


def sqlv(v):
    if v is None:
        return "null"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)


def main():
    en, zh = urls_by_date(DECK_EN), urls_by_date(DECK_ZH)
    rows = []
    with open(MERGED, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            m = re.fullmatch(r"(FY|1Q|1H|9M)(\d{2})", r["period"] or "")
            assert m, f"unparseable period {r['period']!r} at {r['deck_date']}"
            year = 2000 + int(m.group(2))
            obs = f"{year}-{Q_START[m.group(1)]}"
            basis = "IFRS17" if year >= 2026 else "IFRS4"
            url, title = en.get(r["deck_date"], ("", ""))
            if not url:
                url, title = zh.get(r["deck_date"], ("", ""))
            assert url, f"no pdf_url for deck {r['deck_date']}"
            fx_tn = num(r["fx_assets_ntd_tn"])
            res_bn = num(r["fx_volatility_reserve_ntd_bn"])
            cost = num(r["hedging_cost_pct"])
            srcs = ";".join(
                f"{k}={r[k + '_src']}"
                for k in (
                    "fx_assets_ntd_tn", "hedge_cs_ndf_pct", "hedge_proxy_open_pct",
                    "hedge_fvoci_pct", "fx_risk_exposure_pct", "fx_policy_reserve_pct",
                    "hedging_cost_pct", "fx_volatility_reserve_ntd_bn",
                )
                if r.get(k + "_src")
            )
            note_bits = [b for b in (
                f"cost period {r['hedging_cost_period']}" if r.get("hedging_cost_period") else "",
                f"structure as of {r['structure_asof']}" if r.get("structure_asof") else "",
                f"flags {r['flags']}" if r.get("flags") else "",
                f"field sources: {srcs}" if srcs else "",
            ) if b]
            rows.append({
                "obs_quarter": obs,
                "vintage": r["deck_date"],
                "basis": basis,
                "foreign_assets": None if fx_tn is None else round(fx_tn * 1_000_000),
                "fx_reserve_balance": None if res_bn is None else round(res_bn * 1_000),
                "hedge_cost_bp": None if cost is None else round(cost * 100),
                "cs_ndf": num(r["hedge_cs_ndf_pct"]),
                "proxy_open": num(r["hedge_proxy_open_pct"]),
                "fvoci": num(r["hedge_fvoci_pct"]),
                "fx_risk": num(r["fx_risk_exposure_pct"]),
                "fx_policy": num(r["fx_policy_reserve_pct"]),
                "source_url": url,
                "source_doc": f"國泰金控 results deck {r['deck_date']} ({title or 'FX hedging page'}), period {r['period']}",
                "source_note": "; ".join(note_bits) or None,
            })

    keys = {(x["obs_quarter"], x["basis"], x["vintage"]) for x in rows}
    assert len(keys) == len(rows), "duplicate natural keys"

    now = dt.datetime.now(dt.timezone.utc).isoformat()
    cols = ["obs_quarter", "vintage", "basis", "foreign_assets", "fx_reserve_balance",
            "hedge_cost_bp", "cs_ndf", "proxy_open", "fvoci", "fx_risk", "fx_policy",
            "source_url", "source_doc", "source_note"]
    vals = ",\n  ".join(
        "(" + ", ".join(sqlv(x[c]) for c in cols) + ")" for x in rows
    )
    sql = f"""-- stage3-cathay: generated by scripts/stage3_load_cathay.py at {now}. Idempotent.
begin;
with vals({', '.join(cols)}) as (values
  {vals})
insert into tlfx.firm_quarterly
  (entity_id, obs_quarter, vintage, basis, source_channel, foreign_assets,
   fx_reserve_balance, hedge_cost_bp, hedge_cs_ndf_share_pct,
   hedge_proxy_open_share_pct, hedge_fvoci_share_pct, fx_risk_share_pct,
   fx_policy_share_pct, source_url, source_doc, source_note, retrieved_at)
select 'cathay_life', obs_quarter::date, vintage::date, basis::tlfx.accounting_basis,
  'deck', foreign_assets, fx_reserve_balance, hedge_cost_bp, cs_ndf, proxy_open,
  fvoci, fx_risk, fx_policy, source_url, source_doc, source_note,
  '{now}'::timestamptz
from vals
on conflict (entity_id, obs_quarter, basis, source_channel, vintage) do nothing;
commit;
"""
    tag = dt.date.today().strftime("%Y%m%d")
    out = ROOT / "out" / f"stage3_cathay_{tag}.sql"
    out.write_text(sql, encoding="utf-8")

    n = len(rows)
    s_fa = sum(x["foreign_assets"] or 0 for x in rows)
    s_res = sum(x["fx_reserve_balance"] or 0 for x in rows)
    s_bp = sum(x["hedge_cost_bp"] or 0 for x in rows)
    s_cs = sum(x["cs_ndf"] or 0 for x in rows)
    print(f"rows: {n}; quarters {rows[-1]['obs_quarter']} -> {rows[0]['obs_quarter']}")
    print(f"checksums: sum foreign_assets {s_fa}; sum fx_reserve_balance {s_res}; "
          f"sum hedge_cost_bp {s_bp}; sum cs_ndf_share {s_cs}")
    print(f"sql: {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
