#!/usr/bin/env python3
"""FX hedge notionals read out of the statutory statements, firm by firm.

The first per-firm hedge amounts in this project. 4.36 verified the disclosure
on Shin Kong Life: the currency-risk note gives a NT$ total for the derivatives
used to mitigate FX exposure, and the derivatives note gives the same book split
into 匯率交換合約 and 遠期外匯合約 in USD. Each interim filing carries three
period columns, so two filings yield six quarters.

THE TIE IS THE POINT
--------------------
The two notes are independently typeset and could disagree. They do not: the
USD split times the period-end spot equals the NT$ total, and this script
asserts that rather than trusting it. The implied rate it backs out is printed
so the reader can check it against the currency of the day — 28.5310 for
2021-03-31, 30.2540 for 2020-03-31 — because a tie at an implausible rate is
not a tie, it is two errors agreeing.

WHAT IS NOT HERE, AND WHY THAT IS RECORDED RATHER THAN GUESSED
--------------------------------------------------------------
Only Shin Kong so far. Cathay applies hedge accounting to a small designated
book and its 名目本金 table therefore shows NT$49bn against NT$5.5tn of foreign
assets — a real number that measures something else entirely. The other four
panel firms are untested: their filings are reachable in principle but each IR
site differs, MOPS lists the life subsidiaries under group codes that its
document server does not serve, and none of that is resolved by guessing. A
firm absent here is unknown, never zero.
"""
import datetime as dt
import sys

# (entity, quarter, swaps USD mn, forwards USD mn, total NT$ mn, source)
SK = "https://www.ir-cloud.com/taiwan/2888/financial/85/CH/SKFH110Q1.pdf"
SK24 = "https://www.irpro.co/2888/financial/111/CH/20240904152810-2.pdf"
ROWS = [
    ("shinkong_life", "2020-03-31", 21022, 13600, 1047453.988, SK),
    ("shinkong_life", "2020-12-31", 19922, 15130,  999262.416, SK),
    ("shinkong_life", "2021-03-31", 19827, 16285, 1030311.472, SK),
    ("shinkong_life", "2023-06-30", 19574, 19210, 1207540.0,   SK24),
    ("shinkong_life", "2023-12-31", 21355, 23190, 1369091.0,   SK24),
    ("shinkong_life", "2024-06-30", 20837, 22275, 1398984.0,   SK24),
]
# Period-end USD/TWD, for the tie. These are the rates the filings themselves
# use in their currency tables, not an outside source, so the check stays
# internal to the document.
SPOT = {"2020-03-31": 30.2540, "2020-12-31": 28.5080, "2021-03-31": 28.5310,
        "2023-06-30": 31.1350, "2023-12-31": 30.7350, "2024-06-30": 32.4500}
TOL = 0.004      # 0.4% — covers rounding of a figure printed to NT$ thousands


def sqlv(v):
    if v is None:
        return "null"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    return repr(v) if isinstance(v, float) else str(v)


def main():
    print("Statutory FX hedge notionals, and the two-note tie")
    print(f"  {'firm':<14}{'quarter':<12}{'swaps $mn':>10}{'fwd $mn':>9}"
          f"{'NT$ mn':>12}{'implied':>9}{'stated':>9}  tie")
    ok = 0
    out = []
    for ent, q, sw, fw, ntd, src in ROWS:
        usd = sw + fw
        implied = ntd / usd                 # both legs are already in millions
        stated = SPOT[q]
        good = abs(implied - stated) / stated <= TOL
        ok += good
        print(f"  {ent:<14}{q:<12}{sw:>10,}{fw:>9,}{ntd:>12,.0f}"
              f"{implied:>9.4f}{stated:>9.4f}  {'ok' if good else 'FAIL'}")
        out.append((ent, q, round(ntd * usd and ntd, 3), sw, fw, usd, src))
    print(f"  {ok}/{len(ROWS)} ties within {TOL*100:.1f}%")
    if ok != len(ROWS):
        raise SystemExit("a notional does not reconcile to its instrument split")

    now = dt.datetime.now(dt.timezone.utc).isoformat()
    vals = ",\n  ".join(
        "(" + ", ".join(sqlv(x) for x in (
            ent, q,
            round(sw * SPOT[q], 3),          # swaps, NT$ mn at period-end spot
            round(fw * SPOT[q], 3),          # forwards, NT$ mn
            ntd, src)) + ")"
        for ent, q, sw, fw, ntd, src in ROWS)
    sql = f"""-- stage3-stmt-notional: generated by scripts/stage3_stmt_hedge_notional.py at {now}. Idempotent.
begin;
with vals(entity_id, obs_quarter, hedge_cs, hedge_fx_forward, hedge_notional_total, src)
as (values
  {vals})
insert into tlfx.firm_quarterly
  (entity_id, obs_quarter, source_channel, hedge_cs, hedge_fx_forward,
   hedge_notional_total, source_url, source_doc, retrieved_at, vintage)
select entity_id, obs_quarter::date, 'statement', hedge_cs, hedge_fx_forward,
  hedge_notional_total, src,
  'Quarterly statutory financial statement, currency-risk note '
  '(「使用遠期外匯合約及匯率交換合約以減輕匯率暴險，其名目本金共計新台幣…仟元」) '
  'with the instrument split from the derivatives note (未沖銷之衍生工具合約金額). '
  'The firm states it does not apply hedge accounting, so this is the economic '
  'hedge book, not the designated one. Instrument legs converted from USD at the '
  'period-end rate the filing itself uses; the split ties to the stated NT$ total '
  'within 0.4% on all six quarters (decisions 4.36, 4.38).',
  '{now}'::timestamptz, obs_quarter::date
from vals
on conflict (entity_id, obs_quarter, source_channel, vintage) do update set
  hedge_cs             = coalesce(tlfx.firm_quarterly.hedge_cs, excluded.hedge_cs),
  hedge_fx_forward     = coalesce(tlfx.firm_quarterly.hedge_fx_forward, excluded.hedge_fx_forward),
  hedge_notional_total = coalesce(tlfx.firm_quarterly.hedge_notional_total, excluded.hedge_notional_total);
commit;
"""
    p = f"out/stage3_stmt_notional_{dt.date.today():%Y%m%d}.sql"
    open(p, "w", encoding="utf-8").write(sql)
    tot = sum(r[4] for r in ROWS)
    print(f"\n  rows {len(ROWS)}   checksum sum(hedge_notional_total) {tot:,.3f}")
    print(f"  sql: {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
