"""Emit ingestion output: CSV, idempotent SQL, JSON report.

The SQL is the write path for this project: schema `tlfx` is not exposed
through PostgREST, so ingestion scripts render `insert ... on conflict do
nothing` statements that are applied with psql or the Supabase MCP. Every
statement is idempotent on the table's natural key, so re-applying a file is
harmless and revisions (a new vintage) add rows rather than overwrite.
"""
from __future__ import annotations

import csv
import json
from datetime import date
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Iterable

from .provenance import ReconciliationCheck, RunLog, utc_now


def decimal_str(v: Decimal) -> str:
    """Plain decimal text, never scientific notation: 44700, -0.44, 2.5."""
    s = format(v, "f")
    return s.rstrip("0").rstrip(".") if "." in s else s


def sql_literal(v: Any) -> str:
    if v is None or v == "":
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, Decimal):
        return decimal_str(v)
    if isinstance(v, (int, float)):
        return decimal_str(Decimal(str(v)))
    if isinstance(v, date):
        return f"'{v.isoformat()}'"
    s = str(v)
    if not (len(s) == 10 and s[4] == "-" and s[7] == "-"):  # not an ISO date
        try:
            Decimal(s)
            return s
        except InvalidOperation:
            pass
    return "'" + s.replace("'", "''") + "'"


def write_csv(path: Path, rows: list[dict]) -> list[str]:
    path.parent.mkdir(parents=True, exist_ok=True)
    cols = sorted({k for r in rows for k in r})
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow({k: (decimal_str(v) if isinstance(v, Decimal) else v) for k, v in r.items()})
    return cols


def render_sql(*, table: str, conflict: Iterable[str], rows: list[dict], run_id: str, stage: str,
               log: RunLog, checks: list[ReconciliationCheck], generator: str) -> str:
    cols = sorted({k for r in rows for k in r})
    conflict_cols = ", ".join(conflict)
    notes = json.dumps(log.summary(), ensure_ascii=False).replace("'", "''")
    lines = [
        f"-- {stage}: generated by {generator} at {utc_now().isoformat()}. Idempotent.",
        "begin;",
        "insert into tlfx.run_log (run_id, stage, started_at, finished_at, status, notes) values "
        f"('{run_id}', '{stage}', '{log.started_at.isoformat()}', now(), "
        f"'{'fail' if log.failed_checks else 'ok'}', '{notes}'::jsonb) on conflict (run_id) do nothing;",
    ]
    for r in rows:
        vals = ", ".join(sql_literal(r.get(c)) for c in cols)
        lines.append(f"insert into {table} ({', '.join(cols)}) values ({vals}) "
                     f"on conflict ({conflict_cols}) do nothing;")
    for s in log.sources:
        lines.append(
            "insert into tlfx.run_source_status (run_id, source_url, source_doc, http_status, ok, "
            "content_sha256, retrieved_at, note) values "
            f"('{run_id}', {sql_literal(s['source_url'])}, {sql_literal(s['source_doc'])}, "
            f"{sql_literal(s['http_status'])}, {sql_literal(bool(s['ok']))}, {sql_literal(s['content_sha256'])}, "
            f"{sql_literal(s['retrieved_at'])}, {sql_literal(s['note'])}) on conflict (run_id, source_url) do nothing;"
        )
    for c in checks:
        r = c.as_row()
        lines.append(
            "insert into tlfx.run_reconciliation (run_id, check_name, lhs, rhs, tolerance, rel_error, passed, unit) "
            f"values ('{run_id}', {sql_literal(r['check_name'])}, {r['lhs']}, {r['rhs']}, {r['tolerance']}, "
            f"{r['rel_error']}, {sql_literal(r['passed'])}, {sql_literal(r['unit'])}) "
            "on conflict (run_id, check_name) do nothing;"
        )
    lines.append("commit;")
    return "\n".join(lines) + "\n"


def write_report(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
